import Head from "next/head";
import Layout from "../components/Layout/Layout";
import styles from "../styles/Home.module.scss";
import HomeCarousel from "../components/Layout/Carousel/HomeCarousel";
import HomeCard from "../components/Layout/Card/HomeCard";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Commerce | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg/" />
      </Head>

      <Layout>
        <main className={styles.main}>
          <HomeCarousel/>
          <br />
          <HomeCard/>
          HEllo world
        </main>
      </Layout>
    </div>
  );
}
